### ISSUE TITLE
No module named 'natsort'

### ISSUE THREAD

**Issue by soulhighwing** [ashen-sensored/sd_webui_gligen#5]
tried "pip install natsort", although it's been installed, still following error, I believe there must be something need change in a config file somewhere.

Launching Web UI with arguments: --xformers --opt-split-attention
Error loading script: gligen_pluggable.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\stable-diffusion-webui\extensions\sd_webui_gligen\scripts\gligen_pluggable.py", line 8, in <module>
    from natsort import natsorted
ModuleNotFoundError: No module named 'natsort'

**Comment by greyphilosophy** [comment]
This should be resolved by #4 though you'll also have to download the font and do the fix mentioned in #2

**Comment by soulhighwing** [comment]
> This should be resolved by #4 though you'll also have to download the font and do the fix mentioned in #2

it works for me, thank you.
